#!/bin/bash
mkdir -p ./kubeconfigs-processed
mkdir -p ./kubeconfigs-metadata
mkdir -p ./kubeconfigs-targets
mkdir -p ./kubeconfigs-in
KCINPUT="./kubeconfigs-in/*"
KCOUTPATH="./kubeconfigs-processed/*"
KCOUT="./kubeconfigs-processed/"
KCMDT="./kubeconfigs-metadata/"
KCTARGET="./kubeconfigs-targets/" 
for f in $KCINPUT
do
echo "processing $f file"
CLUSTER=$(kubectl config --kubeconfig="$f" view -o jsonpath='{.clusters[*].name}' | sed -e s/lke//g )
cp $f $KCOUT$CLUSTER
NODE=$(kubectl --kubeconfig=$f get nodes -o name | sed 1q)
TOKEN=$(kubectl --kubeconfig=$f debug $NODE -itq --image=curlimages/curl -- curl -X PUT -H 'Metadata-Token-Expiry-Seconds: 3600' http://169.254.169.254/v1/token)
MDT=$(kubectl --kubeconfig=$f debug $NODE -itq --image=curlimages/curl -- curl -H "Metadata-Token: $TOKEN" -H "Accept:application/json" http://169.254.169.254/v1/instance)
cat > "$KCMDT$CLUSTER-mdt" <<EOF
$MDT
EOF
for f in #KCOUTPATH
do
TARGETS=$(kubectl --kubeconfig=$f get nodes -o jsonpath='{.items[*].status.addresses[?(@.type=="ExternalIP")].address}' | sed 's/ /","/g' | sed '1s/^/["/' && echo -n '"]')
cat > "$KCTARGET$CLUSTER-targets" <<EOF
$TARGETS
EOF
done
done

